### PR TITLE
exchange add on

### PR DESCRIPTION
**Pull request by alphaRed03**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

add on exchange chainswap

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
chainswap is now added to the site, i had to fix the code for it though. when you have a moment, please add the xvg erc20 token as well, https://etherscan.io/token/0x85614a474dbeed440d5bbdb8ac50b0f22367f997#balances

**Comment by justinvforvendetta** [comment]
https://github.com/vergecurrency/vergecurrency.com/commit/27e805013f7b99eb8a017c02f7a5d047853a1c8f

**Comment by alphaRed03** [comment]
Okay sure

**Comment by justinvforvendetta** [comment]
does chainswap have a twitter? @alphaRed03 i found an old one that hasnt been used since 2019 https://x.com/chainswap_io

would be good to get some tweets out so the community knows.

also any luck with getting the XVG erc added?

**Comment by alphaRed03** [comment]
Yes Twitter id:
https://twitter.com/chainswap_ex

Yes already info to tech team to addon erc

**Comment by justinvforvendetta** [comment]
ok make a tweet about coin and we will retweet and quote =]

**Comment by justinvforvendetta** [comment]
@XVGETH is our backup, and soon we will have @vergecurrency twitter to use again

**Comment by alphaRed03** [comment]
Yeah it’s done

**Comment by justinvforvendetta** [comment]
excellent! let us know when xvgeth is added, and we will put that across our social media pages too 👍🏼

**Comment by alphaRed03** [comment]
Awesome

**Pull request closed without merging**
