### PR TITLE
Restructuring the homepage HTML by moving sections into partial views 

### PR DESCRIPTION
**Pull request by koenwoortman**

### CODE REVIEW

**Comment by vergecurrency** [comment]
@koenwoortman the site is served from here using jekyll, something in this pr made it break.

**Comment by gfranko** [comment]
Looks like it failed with `Could not find kramdown-1.13.2 in any of the sources`

**Comment by vergecurrency** [comment]
lets see. i added kramdown

**Comment by vergecurrency** [comment]
looks good

**Comment by koenwoortman** [comment]
@gfranko Thanks :). Out of all the changes I didn't expect the ones in the README.md to break the build...

**Pull request merged**
