### PR TITLE
Update es.yml

### PR DESCRIPTION
**Pull request by MenezT**
The whole website translated to spanish.

### CODE REVIEW

**Comment by MenezT** [comment]
The builder keeps showing a syntax error. Already checked the line and column it shows and it's all good for me. Don't know what else I have to do.

**Comment by CryptoRekt** [comment]
Yeah sometimes it does that. Thanks for your hard work.

**Comment by MenezT** [comment]
@CryptoRekt Could you merge the last commit? I made some changes on the structure it's more organized. And thankyou!

**Comment by CryptoRekt** [comment]
Should have auto-added your last commit

**Comment by Yakuza112** [comment]
unable to compile website

`_data/langs/es.yml): did not find expected key while parsing a block mapping at line 463 column 13`

**Pull request merged**
