### PR TITLE
Paper Wallet Imagery Updates

### PR DESCRIPTION
**Pull request by Max1us**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by marpme** [comment]
For some reason, something fails why compiling the website after your changes

**Comment by Max1us** [comment]
That's weird. Is it expecting a specific CRC on the zipfile? I updated the same images in that.

**Comment by Max1us** [comment]
Actually did we update node / npm on the build server recently?

**Comment by Max1us** [comment]
Probably could config for Node 11, but 10 is happy. Node 12 isn't.

**Pull request merged**
