### PR TITLE
Add mining pool

### PR DESCRIPTION
**Pull request by Max1us**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
@ocminer said he was going to delist xvg from his pool

**Comment by ocminer** [comment]
No need to remove them when they're added.. makes sense ??

**Comment by justinvforvendetta** [comment]
@ocminer so you are updating to v6? should we push this to the website?

**Comment by ocminer** [comment]
All pools are updated already, yes

**Comment by Max1us** [comment]
@ocminer Thanks for that - You also might get more hash if you could list the Verge pools on your main Pools page (https://suprnova.cc/) and remove the outdated messages on the https://xvg-mg.suprnova.cc/ pool page.

**Pull request merged**
