### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by Robert941**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jrsikors** [comment]
it's a little more complex than just fixing the .json ... need to fix the reference(s) in the other page(s) that use it.  and we are in the middle of translating a bunch of languages.. so you/we will need to fix it in all the different /locales/XX/ (en, ru, fr)

**Comment by jrsikors** [comment]
@marpme  -- if i go through and fix all the current .json's from infaltion to inflation, as well as the faq page.. do you need to do anything on POEditor to 'pull' the updated faq.json?

**Comment by jrsikors** [comment]
Thanks !  As I mentioned, I'll work with @marpme to see how we can get that fixed everywhere.

**Comment by marpme** [comment]
@Robert941 @jrsikors this just a temporary fix. Please visit our https://poeditor.com/join/project/9nK5XYdOLG repo and check out the english language to fix typos or other stuff there :)

**Pull request merged**
