### PR TITLE
Add link to instructions below each wallet type

### PR DESCRIPTION
**Pull request by jrsikors**
## Types of changes

- [x ] New feature (non-breaking change which adds functionality)
- [x ] Breaking change (fix or feature that would cause existing functionality to change)

Please review this pull request **_carefully_** to see what I'm trying to get at trying to accomplish :smile: 

I will leave it up to you to see if you can make it look prettier.

### CODE REVIEW

**Comment by jrsikors** [comment]
ss1

**Comment by StanFaas** [comment]
@waveon3 please check above image and let me know if you agree with this styling.

**Comment by jrsikors** [comment]
Even I don’t really like the styling.  I’m hoping you can tweak it... make the text smaller and make it fit underneath the “download here”.. make it a different color.. something :)

I just like the idea of putting instruction links on there somewhere!



-Jeff

**Comment by waveon3** [comment]
@jrsikors Looks cool. Yea me and @StanFaas thought the same. We will tweak it and fit it underneath "Download here".

Thanks for your contribution!

**Comment by EdwinB89** [comment]
Improved upon this PR in #364 - Needs review
This can be closed.

**Comment by StanFaas** [comment]
Acknowledged, closed.

**Pull request closed without merging**
