### PR TITLE
Update exchanges.json

### PR DESCRIPTION
**Pull request by alphaRed03**
exchange add on of secureshift.io

secureshift

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
we will need to include the graphic in the PR, otherwise it looks good =]

**Comment by justinvforvendetta** [comment]
@alphaRed03

**Comment by alphaRed03** [comment]
ok sure

**Comment by justinvforvendetta** [comment]
it needs to be in the directory you specified: ../static/img/exchanges/secureshift.png

**Comment by alphaRed03** [comment]
i try to upload but it not giving access to upload

**Comment by alphaRed03** [comment]
it showing : File uploads require push access to this repository.

**Comment by justinvforvendetta** [comment]
you arent pushing you are adding it to your pull request so i can approve it.

**Comment by alphaRed03** [comment]
secureshift
okay

**Comment by justinvforvendetta** [comment]
im guessing you arent familiar with github?

**Comment by alphaRed03** [comment]
check now

**Comment by justinvforvendetta** [comment]
i see it here in the comments but i dont see in the pull request

**Comment by justinvforvendetta** [comment]
got it

**Comment by alphaRed03** [comment]
Thanks

**Comment by justinvforvendetta** [comment]
its now reflecting on the website, thanks

**Comment by alphaRed03** [comment]
Awesome, thanks for the update!

**Pull request merged**
