### PR TITLE
Fixed broken FAQ and P2P page translations and made them dynamic

### PR DESCRIPTION
**Pull request by StanFaas**
**Within this pull request I've changed the following things:**
- Fixed the FAQ and P2P translation issues (no text was displaying when there was no translation).
- Cleaned up the FAQ and P2P html and made the items load dynamically through JavaScript.
- Changed the .yml files into .json files for easy future use with JavaScript.
- Fixed the accordion behaviour by adding `margin:0;` to the `:checked` state.

### CODE REVIEW

**Comment by CryptoRekt** [comment]
Please resolve any conflicts that exist so we can merge this PR.

**Comment by StanFaas** [comment]
Fixed all merge conflicts. Please review and merge in the changes. Thanks!

**Comment by CryptoRekt** [comment]
There are still conflicts in de.yml and fr.yml - please review once more.

**Comment by StanFaas** [comment]
@CryptoRekt errors should be fixed now. Please let me know if there is anything else I can do.

**Comment by justinvforvendetta** [comment]
says theres still several yaml's that have conflicts

**Comment by StanFaas** [comment]
Makes sense, the other languages were changed in the meanwhile. Added them to this PR. So should be resolved.

**Comment by Yakuza112** [comment]
https://i.imgur.com/sKHPqvx.png

nice job :)

working like a charm

**Pull request merged**
